name: Deploy Flask App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/CICDFlaskApp
            git clone https://github.com/Sandeeprajakgithub/CICDFlaskApp.git
            pkill -f app.py || true
            source venv/bin/activate
            python3 app.py
            echo "Deployment completed"